### ISSUE TITLE
挺好的，不过这个是什么情况

### ISSUE THREAD

**Issue by qhzzl** [MegatronKing/SVG-Android#2]
Unable to create application com----android.svg.sample-----.SampleApplication: android.content.res.Resources---$NotFoundException: Resource ID #0x7f02004b

一直报这个错，我看了一下R文件，这个是存在的

**Comment by qhzzl** [comment]
09-08 11:46:44.414 3340-3340/com.android.svg.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.android.svg.sample, PID: 3340
                                                                      java.lang.RuntimeException: Unable to create application com.android.svg.sample.SampleApplication: android.content.res.Resources$NotFoundException: Resource ID #0x7f02003e
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4375)
                                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f02003e
                                                                          at android.content.res.Resources.getValue(Resources.java:1123)
                                                                          at com.android.svg.support.SVGHelper.resKey(SVGHelper.java:34)
                                                                          at com.android.svg.sample.drawables.SVGLoader.add(SVGLoader.java:45)
                                                                          at com.android.svg.sample.drawables.SVGLoader.load(SVGLoader.java:40)
                                                                          at com.android.svg.sample.SampleApplication.onCreate(SampleApplication.java:12)
                                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
                                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5045) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
09-08 11:47:19.058 3340-3340/? I/Process: Sending signal. PID: 3340 SIG: 9

**Comment by MegatronKing** [comment]
android版本是多少

**Comment by MegatronKing** [comment]
低版本无法识别drawable-anydpi下的资源文件，我将自动生成的shape目录改成drawable了，更新下代码现在可以运行了

**Comment by qhzzl** [comment]
ok了
